### ISSUE TITLE
Add transparency parameter

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/samila#90]
#### Description
Add image transparency parameter (`alpha`) to `plot` method

**Comment by evanofslack** [comment]
### Transparency Parameter

I have implemented this on [my branch](https://github.com/evanofslack/samila/tree/alpha).

```python
   def plot(self, color=None, bgcolor=None, spot_size=None, size=None, projection=None, alpha=None):
```

Before I submit a PR I am working to understand this project's test suite so that I can add coverage for this feature. 

#### alpha=0.1 (default)
![alpha_0 1](https://user-images.githubusercontent.com/51209817/150657620-e1e21ee9-140f-4e3b-a06d-5f8bd9e67884.png)

#### alpha=1.0
![alpha_1 0](https://user-images.githubusercontent.com/51209817/150657621-f0704419-588a-44d8-bb30-48b3c81dc99a.png)

**Comment by sadrasabouri** [comment]
Hi @evanofslack !
Do you have any new updates on this issue?
I think providing tests for this feature is very hard we can ignore this feature's tests.
